export type LanguageId = 'en' | 'bn' | 'hi';
export type VoicePlan = 'free' | 'monthly' | 'yearly';

/** Voice returned by the remote API */
export interface ApiVoice {
  voice_id: string;
  name: string;
  character_type: 'male' | 'female';
  voice_type: string; // "free" | "pro" | "pro_max" | …
  profile_photo_url: string | null;
  play_audio_url: string | null;
  /** Mapped from voice_type */
  plan: VoicePlan;
  /** Alias of character_type */
  gender: 'male' | 'female';
}

function mapVoiceType(type: string): VoicePlan {
  if (type === 'free') return 'free';
  if (type === 'pro') return 'monthly';
  return 'yearly'; // pro_max, premium, etc.
}

export async function fetchVoices(): Promise<ApiVoice[]> {
  const res = await fetch('https://gsvtcpiwxaslgusfmzok.supabase.co/functions/v1/voice-list');
  if (!res.ok) throw new Error(`Voice list fetch failed: ${res.status}`);
  const json = await res.json();
  const data: Array<{
    name: string;
    voice_id: string;
    character_type: 'male' | 'female';
    voice_type: string;
    profile_photo_url: string | null;
    play_audio_url: string | null;
  }> = json.data ?? [];
  return data.map((v) => ({
    ...v,
    plan: mapVoiceType(v.voice_type),
    gender: v.character_type,
  }));
}

export interface Language {
  id: LanguageId;
  label: string;
  abbr: string;
  sample: string;
  lang: string; // BCP 47
  placeholder: string;
}

export interface Voice {
  id: string;
  name: string;
  gender: 'male' | 'female';
  accent: string;
  plan: VoicePlan;
  rate: number;
  pitch: number;
}

export const LANGUAGES: Language[] = [
  {
    id: 'bn',
    label: 'বাংলা',
    abbr: 'BN',
    lang: 'bn-BD',
    sample: 'হ্যালো! এটি পারফেক্টরি ভয়েস দ্বারা তৈরি একটি ভয়েস। প্রাকৃতিক বাংলা বক্তৃতা।',
    placeholder: 'এখানে আপনার বাংলা লেখা লিখুন...',
  },
  {
    id: 'en',
    label: 'English',
    abbr: 'EN',
    lang: 'en-US',
    sample: 'Hello! This is a voice generated by Perfectory Voice. Natural AI speech in seconds.',
    placeholder: 'Enter your English text here...',
  },
  {
    id: 'hi',
    label: 'Hindi',
    abbr: 'HI',
    lang: 'hi-IN',
    sample: 'नमस्ते! यह Perfectory Voice द्वारा बनाई गई आवाज़ है। प्राकृतिक हिंदी भाषण।',
    placeholder: 'यहाँ अपना हिंदी पाठ दर्ज करें...',
  },
];

// Plan hierarchy: free < monthly < yearly
// Voice counts: Free 2m+2f, Monthly 5m+5f cumulative, Yearly 10m+10f cumulative
export const VOICES: Voice[] = [
  // ── Free voices (2 male, 2 female) ──────────────────────────────
  { id: 'natural-m',  name: 'Noah',    gender: 'male',   accent: 'Natural',  plan: 'free',    rate: 1.0,  pitch: 1.0  },
  { id: 'casual-m',   name: 'Oliver',  gender: 'male',   accent: 'Casual',   plan: 'free',    rate: 0.97, pitch: 1.03 },
  { id: 'natural-f',  name: 'Aria',    gender: 'female', accent: 'Natural',  plan: 'free',    rate: 1.0,  pitch: 1.08 },
  { id: 'bright-f2',  name: 'Clara',   gender: 'female', accent: 'Bright',   plan: 'free',    rate: 1.02, pitch: 1.14 },
  // ── Monthly Pro voices (+3 male, +3 female = 5m+5f total) ───────
  { id: 'clear-m',    name: 'Marcus',  gender: 'male',   accent: 'Clear',    plan: 'monthly', rate: 0.93, pitch: 0.97 },
  { id: 'strong-m',   name: 'Kyle',    gender: 'male',   accent: 'Strong',   plan: 'monthly', rate: 1.05, pitch: 0.92 },
  { id: 'smooth-m',   name: 'Ryan',    gender: 'male',   accent: 'Smooth',   plan: 'monthly', rate: 0.95, pitch: 1.0  },
  { id: 'warm-f',     name: 'Luna',    gender: 'female', accent: 'Warm',     plan: 'monthly', rate: 0.9,  pitch: 1.12 },
  { id: 'soft-f',     name: 'Zoe',     gender: 'female', accent: 'Soft',     plan: 'monthly', rate: 0.88, pitch: 1.05 },
  { id: 'lively-f',   name: 'Lily',    gender: 'female', accent: 'Lively',   plan: 'monthly', rate: 1.04, pitch: 1.1  },
  // ── Yearly Premium voices (+5 male, +5 female = 10m+10f total) ──
  { id: 'deep-m',     name: 'James',   gender: 'male',   accent: 'Deep',     plan: 'yearly',  rate: 0.88, pitch: 0.82 },
  { id: 'bold-m',     name: 'Ethan',   gender: 'male',   accent: 'Bold',     plan: 'yearly',  rate: 1.08, pitch: 0.88 },
  { id: 'rich-m',     name: 'Alex',    gender: 'male',   accent: 'Rich',     plan: 'yearly',  rate: 0.92, pitch: 0.85 },
  { id: 'noble-m',    name: 'Leo',     gender: 'male',   accent: 'Noble',    plan: 'yearly',  rate: 0.9,  pitch: 0.78 },
  { id: 'refined-m',  name: 'Victor',  gender: 'male',   accent: 'Refined',  plan: 'yearly',  rate: 0.85, pitch: 0.9  },
  { id: 'bright-f',   name: 'Emma',    gender: 'female', accent: 'Bright',   plan: 'yearly',  rate: 1.02, pitch: 1.18 },
  { id: 'gentle-f',   name: 'Sophia',  gender: 'female', accent: 'Gentle',   plan: 'yearly',  rate: 0.85, pitch: 1.1  },
  { id: 'velvety-f',  name: 'Eva',     gender: 'female', accent: 'Velvety',  plan: 'yearly',  rate: 0.88, pitch: 1.06 },
  { id: 'crisp-f',    name: 'Grace',   gender: 'female', accent: 'Crisp',    plan: 'yearly',  rate: 1.0,  pitch: 1.15 },
  { id: 'serene-f',   name: 'Nora',    gender: 'female', accent: 'Serene',   plan: 'yearly',  rate: 0.9,  pitch: 1.08 },
];

export type PlanId = 'free' | 'monthly' | 'yearly';
const PLAN_RANK: Record<PlanId, number> = { free: 0, monthly: 1, yearly: 2 };

export function canUseVoice(userPlan: PlanId, voicePlan: VoicePlan): boolean {
  return PLAN_RANK[userPlan] >= PLAN_RANK[voicePlan];
}

/** Each generation costs exactly 1 credit, regardless of length. */
export function creditCost(_text: string): number {
  return 1;
}

export function speakText(
  text: string,
  language: Language,
  voice: Voice,
  onEnd?: () => void,
  onError?: (msg: string) => void,
): SpeechSynthesisUtterance | null {
  if (!('speechSynthesis' in window)) {
    onError?.('Your browser does not support speech synthesis.');
    return null;
  }
  window.speechSynthesis.cancel();

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang   = language.lang;
  utterance.rate   = voice.rate;
  utterance.pitch  = voice.pitch;
  utterance.volume = 1;

  const voices = window.speechSynthesis.getVoices();
  const match =
    voices.find((v) => v.lang === language.lang) ??
    voices.find((v) => v.lang.startsWith(language.lang.split('-')[0]));
  if (match) utterance.voice = match;

  utterance.onend  = () => onEnd?.();
  utterance.onerror = (e) => {
    if (e.error !== 'interrupted') onError?.(`Speech error: ${e.error}`);
  };

  window.speechSynthesis.speak(utterance);
  return utterance;
}

/** Split text into ≤200-char chunks on word boundaries for TTS download */
export function chunkText(text: string, maxLen = 200): string[] {
  const chunks: string[] = [];
  let remaining = text.trim();
  while (remaining.length > maxLen) {
    let cut = remaining.lastIndexOf(' ', maxLen);
    if (cut < 10) cut = maxLen;
    chunks.push(remaining.slice(0, cut).trim());
    remaining = remaining.slice(cut).trim();
  }
  if (remaining) chunks.push(remaining);
  return chunks;
}
