import { Link } from 'wouter';
import { SiteShell } from '@/components/site-shell';
import { LineBg } from '@/components/line-bg';
import { Icon } from '@/components/icon';
import { Panel, SectionBadge } from '@/components/primitives';
import { SEOHead } from '@/components/seo-head';
import { PAGE_SEO } from '@/lib/seo-config';

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: [
      { sub: '', text: 'By accessing or using Perfectory Voice ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service. We reserve the right to update these Terms at any time; continued use of the Service after changes constitutes acceptance of the revised Terms.' },
    ],
  },
  {
    id: 'eligibility',
    title: '2. Eligibility',
    content: [
      { sub: '', text: 'You must be at least 13 years old to use this Service. By creating an account, you confirm that you meet this age requirement and that the information you provide is accurate and complete. Accounts registered with false information may be suspended or permanently deleted.' },
    ],
  },
  {
    id: 'accounts',
    title: '3. Accounts & Credentials',
    content: [
      { sub: 'Account security', text: 'You are responsible for maintaining the security of your account credentials. Do not share your password with anyone. If you suspect unauthorised access, change your password immediately and notify us.' },
      { sub: 'One account per person', text: 'Each individual may maintain only one active account. Creating multiple accounts to abuse the free credit system is prohibited and will result in all accounts being permanently banned.' },
      { sub: 'Account termination', text: 'We reserve the right to suspend or terminate accounts that violate these Terms, engage in abuse, or remain inactive for more than 12 consecutive months.' },
    ],
  },
  {
    id: 'credits-payments',
    title: '4. Credits & Payments',
    content: [
      { sub: 'Credit system', text: 'The Service operates on a credit-based model. Credits are consumed when generating audio. Credit costs are shown before each generation. We reserve the right to adjust credit costs for new voice tiers with advance notice.' },
      { sub: 'Free credits', text: 'New accounts receive 10 complimentary credits on registration. These credits are non-transferable, have no monetary value, and cannot be redeemed for cash.' },
      { sub: 'Paid plans', text: 'Paid subscription plans are billed in advance on a monthly or annual basis. By subscribing, you authorise us to charge your payment method on a recurring basis.' },
      { sub: 'Refund policy', text: 'Refunds are available within 7 days of purchase if fewer than 20% of the plan\'s credits have been consumed. Requests must be submitted to support@perfectoryvoice.com. Refunds are processed within 5–10 business days.' },
      { sub: 'No credit expiry (purchases)', text: 'Credits purchased directly do not expire. Daily credits provided by subscription plans reset at midnight BST and do not roll over.' },
    ],
  },
  {
    id: 'permitted-use',
    title: '5. Permitted Use',
    content: [
      { sub: 'Allowed', text: 'You may use generated audio for personal projects, educational content, creative works, commercial projects, podcasts, applications, and any other lawful purpose, subject to attribution guidelines.' },
      { sub: 'Prohibited', text: 'You may not use the Service to generate audio that is defamatory, harassing, threatening, obscene, or illegal; to impersonate any person or entity; to create voice deepfakes without consent; or to attempt to reverse-engineer, scrape, or abuse the Service.' },
      { sub: 'AI-generated disclosure', text: 'We encourage users to disclose when content has been AI-generated, particularly in news, political, or educational contexts.' },
    ],
  },
  {
    id: 'intellectual-property',
    title: '6. Intellectual Property',
    content: [
      { sub: 'Your content', text: 'You retain all ownership of the text you input into the Service. You are responsible for ensuring you have the right to use any text you submit (e.g. copyrighted material).' },
      { sub: 'Generated audio', text: 'Audio generated by the Service is provided to you for use in accordance with these Terms. You may use, modify, and distribute generated audio for lawful purposes.' },
      { sub: 'Our platform', text: 'The Perfectory Voice brand, interface, design, codebase, and voice models remain the intellectual property of Perfectory Voice. You may not copy, reproduce, or redistribute any part of the platform itself.' },
    ],
  },
  {
    id: 'privacy',
    title: '7. Privacy',
    content: [
      { sub: '', text: 'Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy to understand our data practices. In summary: we do not store your generated text, we do not sell your data, and all personal information is protected using industry-standard encryption.' },
    ],
  },
  {
    id: 'disclaimers',
    title: '8. Disclaimers & Limitations',
    content: [
      { sub: 'Service availability', text: 'We aim for 99% uptime but do not guarantee uninterrupted access. The Service is provided "as is" without warranties of any kind, express or implied.' },
      { sub: 'Voice accuracy', text: 'AI-generated voices may not be perfectly accurate for all text, especially proper nouns, technical terms, or mixed-script content. We are continuously improving model quality.' },
      { sub: 'Limitation of liability', text: 'To the maximum extent permitted by law, Perfectory Voice shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.' },
    ],
  },
  {
    id: 'changes',
    title: '9. Changes to the Service',
    content: [
      { sub: '', text: 'We reserve the right to modify, suspend, or discontinue any part of the Service at any time. We will provide reasonable advance notice for significant changes that affect paid users. Continued use of the Service after notice of changes constitutes acceptance.' },
    ],
  },
  {
    id: 'governing-law',
    title: '10. Governing Law',
    content: [
      { sub: '', text: 'These Terms are governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the Service shall be resolved through binding arbitration or the courts of competent jurisdiction, as applicable.' },
    ],
  },
  {
    id: 'contact',
    title: '11. Contact',
    content: [
      { sub: '', text: 'For questions about these Terms of Service, please contact us at support@perfectoryvoice.com or use the contact form on our website. We aim to respond to all legal inquiries within 5 business days.' },
    ],
  },
];

export default function TermsPage() {
  return (
    <SiteShell>
      <SEOHead {...PAGE_SEO.terms} />
      {/* ── Hero ─────────────────────────────────────────── */}
      <section className="relative overflow-hidden rounded-3xl border border-border bg-card">
        <LineBg />
        <div className="relative px-6 py-12 text-center sm:px-10 sm:py-16">
          <div className="flex justify-center">

          </div>
          <h1 className="mt-5 text-balance text-4xl leading-tight sm:text-5xl">
            Clear terms, <span className="text-gradient">no surprises</span>
          </h1>
          <p className="mx-auto mt-4 max-w-xl text-pretty text-base leading-relaxed text-muted-foreground">
            These terms govern your use of Perfectory Voice. We've written them to be as clear and fair as possible.
            By using our service, you agree to these terms.
          </p>
          <p className="mt-3 text-xs text-muted-foreground">Last updated: July 2026 · Effective immediately</p>
        </div>
      </section>

      {/* ── Quick summary ─────────────────────────────────── */}
      <div className="mt-6 grid gap-4 sm:grid-cols-3">
        {[
          { icon: 'check', title: 'Plain language', desc: 'No legalese. We explain what we mean in simple terms.' },
          { icon: 'shield', title: 'Fair use', desc: 'Use generated audio for personal and commercial projects freely.' },
          { icon: 'crown', title: 'Your rights', desc: 'You own your text. You control your account. You can delete anytime.' },
        ].map(h => (
          <Panel key={h.title} className="flex items-start gap-3.5 p-5">
            <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-gradient-soft text-brand">
              <Icon name={h.icon as any} size={20} />
            </span>
            <div>
              <p className="text-sm font-semibold">{h.title}</p>
              <p className="mt-0.5 text-xs text-muted-foreground">{h.desc}</p>
            </div>
          </Panel>
        ))}
      </div>

      {/* ── Document ──────────────────────────────────────── */}
      <div className="mt-6 grid gap-6 lg:grid-cols-4">
        {/* TOC */}
        <aside className="hidden lg:block">
          <div className="sticky top-24">
            <Panel className="p-4">
              <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-muted-foreground/70">Contents</p>
              <nav className="flex flex-col gap-0.5">
                {sections.map(s => (
                  <a key={s.id} href={`#${s.id}`}
                    className="rounded-xl px-3 py-2 text-xs text-muted-foreground transition hover:bg-secondary hover:text-foreground">
                    {s.title}
                  </a>
                ))}
              </nav>
            </Panel>
          </div>
        </aside>

        {/* Content */}
        <div className="lg:col-span-3 space-y-4">
          {sections.map(s => (
            <Panel key={s.id} className="p-6 sm:p-7 scroll-mt-24" data-id={s.id}>
              <h2 className="text-lg font-semibold">{s.title}</h2>
              <div className="mt-4 space-y-4">
                {s.content.map((c, i) => (
                  <div key={i}>
                    {c.sub && <p className="mb-1 text-sm font-medium text-foreground">{c.sub}</p>}
                    <p className="text-sm leading-relaxed text-muted-foreground">{c.text}</p>
                  </div>
                ))}
              </div>
            </Panel>
          ))}

          <div className="flex items-start gap-3 rounded-2xl border border-brand/20 bg-gradient-soft px-5 py-4">
            <Icon name="shield" size={18} className="mt-0.5 shrink-0 text-brand-2" />
            <p className="text-sm text-muted-foreground">
              Questions about these terms?{' '}
              <Link href="/contact" className="text-brand-2 hover:underline">Contact our team</Link> — we're always happy to clarify.
            </p>
          </div>
        </div>
      </div>
    </SiteShell>
  );
}
